// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7MuDJ3eRBRuZ0QX3_dGsa-HH8POv5S30',
    appId: '1:291373870320:web:69fb0045479f3db8536635',
    messagingSenderId: '291373870320',
    projectId: 'abacus-b6d57',
    authDomain: 'abacus-b6d57.firebaseapp.com',
    storageBucket: 'abacus-b6d57.firebasestorage.app',
    measurementId: 'G-Y3QBBQPD1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIIDQBffUqZb28bY_m4LEBFRolpXJVFGs',
    appId: '1:291373870320:android:48d82d080c28d304536635',
    messagingSenderId: '291373870320',
    projectId: 'abacus-b6d57',
    storageBucket: 'abacus-b6d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA82-U9vH0O4RUiKSuK2e8GDkjGRAOFBD8',
    appId: '1:291373870320:ios:9e28f0f51cb38065536635',
    messagingSenderId: '291373870320',
    projectId: 'abacus-b6d57',
    storageBucket: 'abacus-b6d57.firebasestorage.app',
    iosBundleId: 'com.example.tajirApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA82-U9vH0O4RUiKSuK2e8GDkjGRAOFBD8',
    appId: '1:291373870320:ios:9e28f0f51cb38065536635',
    messagingSenderId: '291373870320',
    projectId: 'abacus-b6d57',
    storageBucket: 'abacus-b6d57.firebasestorage.app',
    iosBundleId: 'com.example.tajirApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7MuDJ3eRBRuZ0QX3_dGsa-HH8POv5S30',
    appId: '1:291373870320:web:369df9cd7f06401a536635',
    messagingSenderId: '291373870320',
    projectId: 'abacus-b6d57',
    authDomain: 'abacus-b6d57.firebaseapp.com',
    storageBucket: 'abacus-b6d57.firebasestorage.app',
    measurementId: 'G-C13SKGN9MT',
  );

}